language: cpp
os:
  - osx
  - linux

jobs:
  include:
    # macOS Xcode
    - os: osx
      osx_image: xcode11.3
    - os: osx
      osx_image: xcode10.3
    - os: osx
      osx_image: xcode9.4
    - os: osx
      osx_image: xcode11.3
      env:
        - MACOSX_DEPLOYMENT_TARGET="10.12"
    - os: osx
      osx_image: xcode10.3
      env:
        - MACOSX_DEPLOYMENT_TARGET="10.12"
    - os: osx
      osx_image: xcode9.4
      env:
        - MACOSX_DEPLOYMENT_TARGET="10.12"

    # Linux gcc
    - os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - sourceline: “ppa:ubuntu-toolchain-r/test”
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - sourceline: “ppa:ubuntu-toolchain-r/test”
          packages:
            - g++-8
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
    - os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - sourceline: “ppa:ubuntu-toolchain-r/test”
          packages:
            - g++-9
      env:
        - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - cmake -D ENABLE_TESTING:BOOL=TRUE .
  - cmake --build .
  - ctest .
