language: cpp

jobs:
  include:
    # # macOS Xcode
    # - name: Xcode 11.3
    #   os: osx
    #   osx_image: xcode11.3
    # - name: Xcode 10.3
    #   os: osx
    #   osx_image: xcode10.3
    # - name: Xcode 11.3 (macOS 10.12)
    #   os: osx
    #   osx_image: xcode11.3
    #   env:
    #     - MACOSX_DEPLOYMENT_TARGET="10.12"
    # - name: XCode 10.3 (macOS 10.12)
    #   os: osx
    #   osx_image: xcode10.3
    #   env:
    #     - MACOSX_DEPLOYMENT_TARGET="10.12"

    # # Linux gcc
    # - name: gcc 7
    #   os: linux
    #   dist: bionic
    #   addons:
    #     apt:
    #       sources:
    #         - sourceline: “ppa:ubuntu-toolchain-r/test”
    #       packages:
    #         - g++-7
    #   env:
    #     - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    # - name: gcc 8
    #   os: linux
    #   dist: bionic
    #   addons:
    #     apt:
    #       sources:
    #         - sourceline: “ppa:ubuntu-toolchain-r/test”
    #       packages:
    #         - g++-8
    #   env:
    #     - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
    # - name: gcc 9
    #   os: linux
    #   dist: bionic
    #   addons:
    #     apt:
    #       sources:
    #         - sourceline: “ppa:ubuntu-toolchain-r/test”
    #       packages:
    #         - g++-9
    #   env:
    #     - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"

    # # Linux clang
    # - name: clang 5
    #   os: linux
    #   dist: bionic
    #   addons:
    #     apt:
    #       sources:
    #         - sourceline: "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-5.0 main"
    #           key_url: "https://apt.llvm.org/llvm-snapshot.gpg.key"
    #       packages:
    #         - clang-5.0
    #   env:
    #     - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
    # - name: clang 6
    #   os: linux
    #   dist: bionic
    #   addons:
    #     apt:
    #       sources:
    #         - sourceline: "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-6.0 main"
    #           key_url: "https://apt.llvm.org/llvm-snapshot.gpg.key"
    #       packages:
    #         - clang-6.0
    #   env:
    #     - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"
    # - name: clang 7
    #   os: linux
    #   dist: bionic
    #   addons:
    #     apt:
    #       sources:
    #         - sourceline: "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-7 main"
    #           key_url: "https://apt.llvm.org/llvm-snapshot.gpg.key"
    #       packages:
    #         - clang-7
    #   env:
    #     - MATRIX_EVAL="CC=clang-7 && CXX=clang++-7"
    - name: clang 8
      os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - sourceline: "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-8 main"
              key_url: "https://apt.llvm.org/llvm-snapshot.gpg.key"
          packages:
            - clang-8
      env:
        - MATRIX_EVAL="CC=clang-8 && CXX=clang++-8"
    - name: clang 9
      os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - sourceline: "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main"
              key_url: "https://apt.llvm.org/llvm-snapshot.gpg.key"
          packages:
            - clang-9
      env:
        - MATRIX_EVAL="CC=clang-9 && CXX=clang++-9"
    - name: clang 10
      os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - sourceline: "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-10 main"
              key_url: "https://apt.llvm.org/llvm-snapshot.gpg.key"
          packages:
            - clang-10
      env:
        - MATRIX_EVAL="CC=clang-10 && CXX=clang++-10"
    - name: clang 11
      os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - sourceline: "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic main"
              key_url: "https://apt.llvm.org/llvm-snapshot.gpg.key"
          packages:
            - clang-11
      env:
        - MATRIX_EVAL="CC=clang-11 && CXX=clang++-11"

    # # Windows MSVC
    # - name: Windows (MSVC)
    #   os: windows

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - cmake -DENABLE_TESTING:BOOL=TRUE -DCMAKE_BUILD_TYPE=RelWithDebInfo .
  - cmake --build .
  - ctest .
