language: cpp
os:
  - osx

jobs:
  include:
    # macOS Xcode
    - os: osx
      osx_image: xcode11.3
    - os: osx
      osx_image: xcode10.3
    - os: osx
      osx_image: xcode9.4
    - os: osx
      osx_image: xcode11.3
      env:
        - MACOSX_DEPLOYMENT_TARGET="10.12"
    - os: osx
      osx_image: xcode10.3
      env:
        - MACOSX_DEPLOYMENT_TARGET="10.12"
    - os: osx
      osx_image: xcode9.4
      env:
        - MACOSX_DEPLOYMENT_TARGET="10.12"
script:
  - cmake -D ENABLE_TESTING:BOOL=TRUE .
  - cmake --build .
  - ctest .
