language: cpp

os:
  - osx
  - linux
  - windows

compiler:
  - gcc
  - clang

before_script:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update                ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install abseil catch2 ; fi

script:
  - cmake -D ENABLE_TESTING:BOOL=TRUE .
  - cmake --build .
  - ctest .
