language: cpp

branches:
  only:
    - master

jobs:
  include:
    # macOS Xcode
    - name: Xcode 13.2
      os: osx
      osx_image: xcode13.2
    - name: Xcode 10.3
      os: osx
      osx_image: xcode10.3
    - name: Xcode 10.3 (targeting macOS 10.12)
      os: osx
      osx_image: xcode10.3
      env:
        - MACOSX_DEPLOYMENT_TARGET="10.12"
    - name: Xcode 13.2 (targeting macOS 10.12)
      os: osx
      osx_image: xcode13.2
      env:
        - MACOSX_DEPLOYMENT_TARGET="10.12"

    # Linux gcc
    - name: gcc 7
      os: linux
      dist: focal
      addons:
        apt:
          sources:
            - sourceline: “ppa:ubuntu-toolchain-r/test”
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - name: gcc 11
      os: linux
      dist: focal
      addons:
        apt:
          sources:
            - sourceline: “ppa:ubuntu-toolchain-r/test”
          packages:
            - g++-11
      env:
        - MATRIX_EVAL="CC=gcc-11 && CXX=g++-11"

    # Linux clang
    - name: clang 5
      os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - sourceline: "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-5.0 main"
              key_url: "https://apt.llvm.org/llvm-snapshot.gpg.key"
            - sourceline: 'deb https://apt.kitware.com/ubuntu/ bionic main'
              key_url: 'https://apt.kitware.com/keys/kitware-archive-latest.asc'
          packages:
            - clang-5.0
            - cmake
      env:
        - MATRIX_EVAL="PATH=/usr/bin:$PATH && CC=clang-5.0 && CXX=clang++-5.0"
    - name: clang 13
      os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - sourceline: "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-13 main"
              key_url: "https://apt.llvm.org/llvm-snapshot.gpg.key"
            - sourceline: 'deb https://apt.kitware.com/ubuntu/ bionic main'
              key_url: 'https://apt.kitware.com/keys/kitware-archive-latest.asc'
          packages:
            - clang-13
            - cmake
      env:
        - MATRIX_EVAL="PATH=/usr/bin:$PATH && CC=clang-13 && CXX=clang++-13"
  
    # Windows MSVC
    - name: Windows (MSVC 2019)
      os: windows
      install:
        - choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64"
      script:
        - cmake -G "Visual Studio 16 2019" .
        - cmake --build .
        - ctest .
    - name: Windows (MSVC 2022)
      os: windows
      install:
        - choco upgrade cmake
        - choco install visualstudio2022buildtools --package-parameters "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64"
      script:
        - cmake -G "Visual Studio 17 2022" .
        - cmake --build .
        - ctest .

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - cmake .
  - cmake --build .
  - ctest .
