language: cpp

jobs:
  include:
    # macOS Xcode
    - os: osx
      osx_image: xcode11.3
    - os: osx
      osx_image: xcode10.3
    - os: osx
      osx_image: xcode9.4
    - os: osx
      osx_image: xcode11.3
      env:
        - MACOSX_DEPLOYMENT_TARGET="10.12"
    - os: osx
      osx_image: xcode10.3
      env:
        - MACOSX_DEPLOYMENT_TARGET="10.12"
    - os: osx
      osx_image: xcode9.4
      env:
        - MACOSX_DEPLOYMENT_TARGET="10.12"

    # Linux gcc
    - os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - sourceline: “ppa:ubuntu-toolchain-r/test”
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - sourceline: “ppa:ubuntu-toolchain-r/test”
          packages:
            - g++-8
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
    - os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - sourceline: “ppa:ubuntu-toolchain-r/test”
          packages:
            - g++-9
      env:
        - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"

    # Linux clang
    - os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - sourceline: "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-5.0 main"
              key_url: "https://apt.llvm.org/llvm-snapshot.gpg.key"
          packages:
            - clang-5.0
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
    - os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - sourceline: "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-6.0 main"
              key_url: "https://apt.llvm.org/llvm-snapshot.gpg.key"
          packages:
            - clang-6.0
      env:
        - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"
    - os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - sourceline: "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-7 main"
              key_url: "https://apt.llvm.org/llvm-snapshot.gpg.key"
          packages:
            - clang-7
      env:
        - MATRIX_EVAL="CC=clang-7 && CXX=clang++-7"
    - os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - sourceline: "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-8 main"
              key_url: "https://apt.llvm.org/llvm-snapshot.gpg.key"
          packages:
            - clang-8
      env:
        - MATRIX_EVAL="CC=clang-8 && CXX=clang++-8"
    - os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - sourceline: "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main"
              key_url: "https://apt.llvm.org/llvm-snapshot.gpg.key"
          packages:
            - clang-9
      env:
        - MATRIX_EVAL="CC=clang-9 && CXX=clang++-9"
    - os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - sourceline: "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-10 main"
              key_url: "https://apt.llvm.org/llvm-snapshot.gpg.key"
          packages:
            - clang-10
      env:
        - MATRIX_EVAL="CC=clang-10 && CXX=clang++-10"
    - os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - sourceline: "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic main"
              key_url: "https://apt.llvm.org/llvm-snapshot.gpg.key"
          packages:
            - clang-11
      env:
        - MATRIX_EVAL="CC=clang-11 && CXX=clang++-11"

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - cmake -D ENABLE_TESTING:BOOL=TRUE .
  - cmake --build .
  - ctest .
